### ISSUE TITLE
The benchmark structure/

### ISSUE THREAD

**Issue by babatn1** [paularmstrong/react-component-benchmark#1]
Dear everyone; I want to understand What is the benchmark structure?
Please, who everyone to know it? could you send me or share for me any document related for it?
Many thanks!

**Comment by paularmstrong** [comment]
I don't understand your question.

Did you read the [README](https://github.com/paularmstrong/react-component-benchmark/tree/master/README.md)?
Did you look at the [examples](https://github.com/paularmstrong/react-component-benchmark/tree/master/examples)

**Comment by babatn1** [comment]
Dear @paularmstrong ;
I mean is I want to understand to The benchmark structure. Do you have any document about The benchmark structure?

**Comment by paularmstrong** [comment]
Literally in the docs. https://github.com/paularmstrong/react-component-benchmark#results
